# Why NumPy is for working with data

NumPy, an acronym for the term ‘Numerical Python’, is a library in Python which is used extensively for efficient mathematical computing. This library allows users to store large amounts of data using less memory and perform extensive operations efficiently. It provides optimised and simpler functionalities to perform aforementioned operations using homogenous, one-dimensional and multidimensional arrays.

Now, before delving deep into the concept of NumPy arrays, it is important to note that Python lists can very well perform all the actions that NumPy arrays perform; it is simply the fact that NumPy arrays are faster and more convenient than lists when it comes to extensive computations, which make them extremely useful, especially when you are working with large amounts of data.

The basic data structure of NumPy is an array. A NumPy array is a collection of values stored together, similar to a list. 

Advantages of using NumPy arrays over normal lists are :

1. Ability to operate on individual elements in the array without using loops or list comprehension
2. Speed of execution 

## Numpy vs Lists 

In [13]:
#Let's define a list in python.
heights = [74, 75, 72, 72, 71]

In [14]:
# Print the heights.
heights

[74, 75, 72, 72, 71]

In [15]:
# Try to multiple heights with a scalar.
heights * 2.54

TypeError: can't multiply sequence by non-int of type 'float'

In [16]:
import numpy as np

In [17]:
# Define a NumPy array
np_heights = np.array([74, 75, 72, 72, 71])

In [5]:
np_heights

array([74, 75, 72, 72, 71])

In [6]:
# Print the type of a NumPy array.
type(np_heights)

numpy.ndarray

In [9]:
# Multiple height (NumPy array) with a scalar.
np_heights * 2.54

array([187.96, 190.5 , 182.88, 182.88, 180.34])


#### NumPy comes with its own set of methods and operations

In [10]:
# Let's define two lists and perform '+' operation on that.
list_1 = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [11]:
# Let's define two NumPy array and perform '+' operation on that.
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
np1 + np2

array([5, 7, 9])

#### NumPy Array VS List

The only difference between a NumPy array and a list is that the elements in the NumPy array are separated by a space instead of a comma. Hence, this is an aesthetic feature that differentiates a list and a NumPy array.

NumPy Arrays are homogeneous in nature. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which could be an integer, float, string, etc. 

In [7]:
print(np_heights)

[74 75 72 72 71]


In [11]:
a = np.array([1.0, 2, 3.5, 0.2, True])


numpy.ndarray